/*
 * litegraph-patches.js — Patron's EXTERNAL customization layer for litegraph.
 *
 * The vendored vendor/litegraph/litegraph.js is kept BYTE-FOR-BYTE PRISTINE so a new
 * upstream version is a pure drop-in (no fork, no in-file edits). Every Patron render
 * tweak lives here instead, as prototype overrides applied AFTER the library loads.
 * Each override is the upstream method with Patron changes marked /* PATRON: ... *​/ inline.
 *
 * Overrides (all on LGraphCanvas.prototype):
 *   drawNode           - small-caps connector labels, +2px label align, +5px widget gap
 *   drawNodeShape      - 1px node border (LiteGraph.NODE_BORDER_COLOR), 0.5px title sep,
 *                        bolder selection border
 *   renderLink         - themeable selected-link highlight (LiteGraph.LINK_HIGHLIGHT_COLOR)
 *                        [the upstream IIFE-local distance() is reached via LiteGraph.distance]
 *   processContextMenu - friendly node title (getTitle) instead of the internal type path
 *
 * The globals these read (NODE_BORDER_COLOR, LINK_HIGHLIGHT_COLOR) are set per-theme by
 * js/app.js. If litegraph is updated and any of these methods change upstream, RE-EXTRACT
 * them here — this file is the ONLY place that needs attention; the vendored file stays pristine.
 *
 * Generated by extracting the working methods from litegraph 0.4 (not hand-transcribed).
 */
(function (global) {
  "use strict";
  var LiteGraph = global.LiteGraph, LGraphCanvas = global.LGraphCanvas, LGraphNode = global.LGraphNode;
  if (!LiteGraph || !LGraphCanvas) { console.error("litegraph-patches: litegraph not loaded first"); return; }

  // ---- LGraphNode.prototype.getConnectionPos ----
  // PATRON: inset the IN/OUT connector dots ~20px inward from the node's left/right borders so
  // they aren't flush with the edge. Links use getConnectionPos, so the wires follow the dots
  // automatically. Only the default vertical-slot path is inset (collapsed / horizontal /
  // hard-coded slot.pos layouts are left as-is).
  if (LGraphNode && LGraphNode.prototype.getConnectionPos) {
    var _patronGetConnPos = LGraphNode.prototype.getConnectionPos;
    var PATRON_SLOT_INSET = 10;
    LGraphNode.prototype.getConnectionPos = function (is_input, slot_number, out) {
      out = _patronGetConnPos.call(this, is_input, slot_number, out);
      var slot = is_input
        ? (this.inputs && this.inputs[slot_number])
        : (this.outputs && this.outputs[slot_number]);
      var hardcoded = slot && slot.pos; // respect an explicit per-slot position
      if (!this.flags.collapsed && !this.horizontal && !hardcoded && slot_number >= 0) {
        out[0] += is_input ? PATRON_SLOT_INSET : -PATRON_SLOT_INSET;
      }
      return out;
    };
  }

  // The extracted drawNode/drawNodeShape below use litegraph's module-local scratch
  // arrays, which are NOT in scope here (the vendored file is a closed IIFE). Provide our
  // own — matching the vendor's declarations — so the overrides don't throw
  // "<name> is not defined" and abort node rendering.
  var temp_vec2 = new Float32Array(2);   // vendor litegraph.js:8535 (drawNode)
  var tmp_area = new Float32Array(4);     // vendor litegraph.js:9030 (drawNodeShape)

  // ---- LGraphCanvas.prototype.drawNode ----
  LGraphCanvas.prototype.drawNode = function(node, ctx) {
        var glow = false;
        this.current_node = node;

        var color = node.color || node.constructor.color || LiteGraph.NODE_DEFAULT_COLOR;
        var bgcolor = node.bgcolor || node.constructor.bgcolor || LiteGraph.NODE_DEFAULT_BGCOLOR;

        //shadow and glow
        if (node.mouseOver) {
            glow = true;
        }

        var low_quality = this.ds.scale < 0.6; //zoomed out

        //only render if it forces it to do it
        if (this.live_mode) {
            if (!node.flags.collapsed) {
                ctx.shadowColor = "transparent";
                if (node.onDrawForeground) {
                    node.onDrawForeground(ctx, this, this.canvas);
                }
            }
            return;
        }

        var editor_alpha = this.editor_alpha;
        ctx.globalAlpha = editor_alpha;

        if (this.render_shadows && !low_quality) {
            ctx.shadowColor = LiteGraph.DEFAULT_SHADOW_COLOR;
            ctx.shadowOffsetX = 2 * this.ds.scale;
            ctx.shadowOffsetY = 2 * this.ds.scale;
            ctx.shadowBlur = 3 * this.ds.scale;
        } else {
            ctx.shadowColor = "transparent";
        }

        //custom draw collapsed method (draw after shadows because they are affected)
        if (
            node.flags.collapsed &&
            node.onDrawCollapsed &&
            node.onDrawCollapsed(ctx, this) == true
        ) {
            return;
        }

        //clip if required (mask)
        var shape = node._shape || LiteGraph.BOX_SHAPE;
        var size = temp_vec2;
        temp_vec2.set(node.size);
        var horizontal = node.horizontal; // || node.flags.horizontal;

        if (node.flags.collapsed) {
            ctx.font = this.inner_text_font;
            var title = node.getTitle ? node.getTitle() : node.title;
            if (title != null) {
                node._collapsed_width = Math.min(
                    node.size[0],
                    ctx.measureText(title).width +
                        LiteGraph.NODE_TITLE_HEIGHT * 2
                ); //LiteGraph.NODE_COLLAPSED_WIDTH;
                size[0] = node._collapsed_width;
                size[1] = 0;
            }
        }

        if (node.clip_area) {
            //Start clipping
            ctx.save();
            ctx.beginPath();
            if (shape == LiteGraph.BOX_SHAPE) {
                ctx.rect(0, 0, size[0], size[1]);
            } else if (shape == LiteGraph.ROUND_SHAPE) {
                ctx.roundRect(0, 0, size[0], size[1], [10]);
            } else if (shape == LiteGraph.CIRCLE_SHAPE) {
                ctx.arc(
                    size[0] * 0.5,
                    size[1] * 0.5,
                    size[0] * 0.5,
                    0,
                    Math.PI * 2
                );
            }
            ctx.clip();
        }

        //draw shape
        if (node.has_errors) {
            bgcolor = "red";
        }
        this.drawNodeShape(
            node,
            ctx,
            size,
            color,
            bgcolor,
            node.is_selected,
            node.mouseOver
        );
        ctx.shadowColor = "transparent";

        //draw foreground
        if (node.onDrawForeground) {
            node.onDrawForeground(ctx, this, this.canvas);
        }

        //connection slots
        ctx.textAlign = horizontal ? "center" : "left";
        ctx.font = "normal small-caps " + (LiteGraph.NODE_SUBTEXT_SIZE - 1) + "px 'Roboto', sans-serif"; /* PATRON: small-caps connector labels, 1px smaller */

        var render_text = !low_quality;

        var out_slot = this.connecting_output;
        var in_slot = this.connecting_input;
        ctx.lineWidth = 1;

        var max_y = 0;
        var slot_pos = new Float32Array(2); //to reuse

        //render inputs and outputs
        if (!node.flags.collapsed) {
            //input connection slots
            ctx.strokeStyle = "black"; /* PATRON: inputs get the SAME dot border as outputs (was output-only) */
            if (node.inputs) {
                for (var i = 0; i < node.inputs.length; i++) {
                    var slot = node.inputs[i];
                    
                    var slot_type = slot.type;
                    var slot_shape = slot.shape;
                    
                    ctx.globalAlpha = editor_alpha;
                    //change opacity of incompatible slots when dragging a connection
                    if ( this.connecting_output && !LiteGraph.isValidConnection( slot.type , out_slot.type) ) {
                        ctx.globalAlpha = 0.4 * editor_alpha;
                    }

                    ctx.fillStyle =
                        slot.link != null
                            ? slot.color_on ||
                              this.default_connection_color_byType[slot_type] ||
                              this.default_connection_color.input_on
                            : slot.color_off ||
                              this.default_connection_color_byTypeOff[slot_type] ||
                              this.default_connection_color_byType[slot_type] ||
                              this.default_connection_color.input_off;

                    var pos = node.getConnectionPos(true, i, slot_pos);
                    pos[0] -= node.pos[0];
                    pos[1] -= node.pos[1];
                    if (max_y < pos[1] + LiteGraph.NODE_SLOT_HEIGHT * 0.5) {
                        max_y = pos[1] + LiteGraph.NODE_SLOT_HEIGHT * 0.5;
                    }

                    ctx.beginPath();

					if (slot_type == "array"){
                        slot_shape = LiteGraph.GRID_SHAPE; // place in addInput? addOutput instead?
                    }
                    
                    var doStroke = true;
                    
                    if (
                        slot.type === LiteGraph.EVENT ||
                        slot.shape === LiteGraph.BOX_SHAPE
                    ) {
                        if (horizontal) {
                            ctx.rect(
                                pos[0] - 5 + 0.5,
                                pos[1] - 8 + 0.5,
                                10,
                                14
                            );
                        } else {
                            ctx.rect(
                                pos[0] - 6 + 0.5,
                                pos[1] - 5 + 0.5,
                                14,
                                10
                            );
                        }
                    } else if (slot_shape === LiteGraph.ARROW_SHAPE) {
                        ctx.moveTo(pos[0] + 8, pos[1] + 0.5);
                        ctx.lineTo(pos[0] - 4, pos[1] + 6 + 0.5);
                        ctx.lineTo(pos[0] - 4, pos[1] - 6 + 0.5);
                        ctx.closePath();
                    } else if (slot_shape === LiteGraph.GRID_SHAPE) {
                        ctx.rect(pos[0] - 4, pos[1] - 4, 2, 2);
                        ctx.rect(pos[0] - 1, pos[1] - 4, 2, 2);
                        ctx.rect(pos[0] + 2, pos[1] - 4, 2, 2);
                        ctx.rect(pos[0] - 4, pos[1] - 1, 2, 2);
                        ctx.rect(pos[0] - 1, pos[1] - 1, 2, 2);
                        ctx.rect(pos[0] + 2, pos[1] - 1, 2, 2);
                        ctx.rect(pos[0] - 4, pos[1] + 2, 2, 2);
                        ctx.rect(pos[0] - 1, pos[1] + 2, 2, 2);
                        ctx.rect(pos[0] + 2, pos[1] + 2, 2, 2);
                        doStroke = false;
                    } else {
						if(low_quality)
	                        ctx.rect(pos[0] - 4, pos[1] - 4, 8, 8 ); //faster
						else
	                        ctx.arc(pos[0], pos[1], 4, 0, Math.PI * 2);
                    }
                    ctx.fill();
                    if(!low_quality && doStroke) /* PATRON: match the output dot border */
                        ctx.stroke();

                    //render name
                    if (render_text) {
                        var text = slot.label != null ? slot.label : slot.name;
                        if (text) {
                            ctx.fillStyle = LiteGraph.NODE_TEXT_COLOR;
                            if (horizontal || slot.dir == LiteGraph.UP) {
                                ctx.fillText(text, pos[0], pos[1] - 10);
                            } else {
                                ctx.fillText(text, pos[0] + 10, pos[1] + 3); /* PATRON: up 2px to align with the slot dot */
                            }
                        }
                    }
                }
            }

            //output connection slots

            ctx.textAlign = horizontal ? "center" : "right";
            ctx.strokeStyle = "black";
            if (node.outputs) {
                for (var i = 0; i < node.outputs.length; i++) {
                    var slot = node.outputs[i];
                    
                    var slot_type = slot.type;
                    var slot_shape = slot.shape;
                    
                    //change opacity of incompatible slots when dragging a connection
                    if (this.connecting_input && !LiteGraph.isValidConnection( slot_type , in_slot.type) ) {
                        ctx.globalAlpha = 0.4 * editor_alpha;
                    }
                    
                    var pos = node.getConnectionPos(false, i, slot_pos);
                    pos[0] -= node.pos[0];
                    pos[1] -= node.pos[1];
                    if (max_y < pos[1] + LiteGraph.NODE_SLOT_HEIGHT * 0.5) {
                        max_y = pos[1] + LiteGraph.NODE_SLOT_HEIGHT * 0.5;
                    }

                    ctx.fillStyle =
                        slot.links && slot.links.length
                            ? slot.color_on ||
                              this.default_connection_color_byType[slot_type] ||
                              this.default_connection_color.output_on
                            : slot.color_off ||
                              this.default_connection_color_byTypeOff[slot_type] ||
                              this.default_connection_color_byType[slot_type] ||
                              this.default_connection_color.output_off;
                    ctx.beginPath();
                    //ctx.rect( node.size[0] - 14,i*14,10,10);

					if (slot_type == "array"){
                        slot_shape = LiteGraph.GRID_SHAPE;
                    }
                    
                    var doStroke = true;
                    
                    if (
                        slot_type === LiteGraph.EVENT ||
                        slot_shape === LiteGraph.BOX_SHAPE
                    ) {
                        if (horizontal) {
                            ctx.rect(
                                pos[0] - 5 + 0.5,
                                pos[1] - 8 + 0.5,
                                10,
                                14
                            );
                        } else {
                            ctx.rect(
                                pos[0] - 6 + 0.5,
                                pos[1] - 5 + 0.5,
                                14,
                                10
                            );
                        }
                    } else if (slot_shape === LiteGraph.ARROW_SHAPE) {
                        ctx.moveTo(pos[0] + 8, pos[1] + 0.5);
                        ctx.lineTo(pos[0] - 4, pos[1] + 6 + 0.5);
                        ctx.lineTo(pos[0] - 4, pos[1] - 6 + 0.5);
                        ctx.closePath();
                    }  else if (slot_shape === LiteGraph.GRID_SHAPE) {
                        ctx.rect(pos[0] - 4, pos[1] - 4, 2, 2);
                        ctx.rect(pos[0] - 1, pos[1] - 4, 2, 2);
                        ctx.rect(pos[0] + 2, pos[1] - 4, 2, 2);
                        ctx.rect(pos[0] - 4, pos[1] - 1, 2, 2);
                        ctx.rect(pos[0] - 1, pos[1] - 1, 2, 2);
                        ctx.rect(pos[0] + 2, pos[1] - 1, 2, 2);
                        ctx.rect(pos[0] - 4, pos[1] + 2, 2, 2);
                        ctx.rect(pos[0] - 1, pos[1] + 2, 2, 2);
                        ctx.rect(pos[0] + 2, pos[1] + 2, 2, 2);
                        doStroke = false;
                    } else {
						if(low_quality)
	                        ctx.rect(pos[0] - 4, pos[1] - 4, 8, 8 );
						else
	                        ctx.arc(pos[0], pos[1], 4, 0, Math.PI * 2);
                    }

                    //trigger
                    //if(slot.node_id != null && slot.slot == -1)
                    //	ctx.fillStyle = "#F85";

                    //if(slot.links != null && slot.links.length)
                    ctx.fill();
					if(!low_quality && doStroke)
	                    ctx.stroke();

                    //render output name
                    if (render_text) {
                        var text = slot.label != null ? slot.label : slot.name;
                        if (text) {
                            ctx.fillStyle = LiteGraph.NODE_TEXT_COLOR;
                            if (horizontal || slot.dir == LiteGraph.DOWN) {
                                ctx.fillText(text, pos[0], pos[1] - 8);
                            } else {
                                ctx.fillText(text, pos[0] - 10, pos[1] + 3); /* PATRON: up 2px to align with the slot dot */
                            }
                        }
                    }
                }
            }

            ctx.textAlign = "left";
            ctx.globalAlpha = 1;

            if (node.widgets) {
				var widgets_y = max_y + 5; /* PATRON: +5px gap between connector labels and first widget */
                if (horizontal || node.widgets_up) {
                    widgets_y = 2;
                }
				if( node.widgets_start_y != null )
                    widgets_y = node.widgets_start_y;
                ctx.font = this.inner_text_font; /* PATRON: reset — small-caps is ONLY for connector labels, not widgets */
                this.drawNodeWidgets(
                    node,
                    widgets_y,
                    ctx,
                    this.node_widget && this.node_widget[0] == node
                        ? this.node_widget[1]
                        : null
                );
            }
        } else if (this.render_collapsed_slots) {
            //if collapsed
            var input_slot = null;
            var output_slot = null;

            //get first connected slot to render
            if (node.inputs) {
                for (var i = 0; i < node.inputs.length; i++) {
                    var slot = node.inputs[i];
                    if (slot.link == null) {
                        continue;
                    }
                    input_slot = slot;
                    break;
                }
            }
            if (node.outputs) {
                for (var i = 0; i < node.outputs.length; i++) {
                    var slot = node.outputs[i];
                    if (!slot.links || !slot.links.length) {
                        continue;
                    }
                    output_slot = slot;
                }
            }

            if (input_slot) {
                var x = 0;
                var y = LiteGraph.NODE_TITLE_HEIGHT * -0.5; //center
                if (horizontal) {
                    x = node._collapsed_width * 0.5;
                    y = -LiteGraph.NODE_TITLE_HEIGHT;
                }
                ctx.fillStyle = "#686";
                ctx.beginPath();
                if (
                    slot.type === LiteGraph.EVENT ||
                    slot.shape === LiteGraph.BOX_SHAPE
                ) {
                    ctx.rect(x - 7 + 0.5, y - 4, 14, 8);
                } else if (slot.shape === LiteGraph.ARROW_SHAPE) {
                    ctx.moveTo(x + 8, y);
                    ctx.lineTo(x + -4, y - 4);
                    ctx.lineTo(x + -4, y + 4);
                    ctx.closePath();
                } else {
                    ctx.arc(x, y, 4, 0, Math.PI * 2);
                }
                ctx.fill();
            }

            if (output_slot) {
                var x = node._collapsed_width;
                var y = LiteGraph.NODE_TITLE_HEIGHT * -0.5; //center
                if (horizontal) {
                    x = node._collapsed_width * 0.5;
                    y = 0;
                }
                ctx.fillStyle = "#686";
                ctx.strokeStyle = "black";
                ctx.beginPath();
                if (
                    slot.type === LiteGraph.EVENT ||
                    slot.shape === LiteGraph.BOX_SHAPE
                ) {
                    ctx.rect(x - 7 + 0.5, y - 4, 14, 8);
                } else if (slot.shape === LiteGraph.ARROW_SHAPE) {
                    ctx.moveTo(x + 6, y);
                    ctx.lineTo(x - 6, y - 4);
                    ctx.lineTo(x - 6, y + 4);
                    ctx.closePath();
                } else {
                    ctx.arc(x, y, 4, 0, Math.PI * 2);
                }
                ctx.fill();
                //ctx.stroke();
            }
        }

        if (node.clip_area) {
            ctx.restore();
        }

        ctx.globalAlpha = 1.0;
    };

  // ---- LGraphCanvas.prototype.drawNodeShape ----
  LGraphCanvas.prototype.drawNodeShape = function(
        node,
        ctx,
        size,
        fgcolor,
        bgcolor,
        selected,
        mouse_over
    ) {
        //bg rect
        ctx.strokeStyle = fgcolor;
        ctx.fillStyle = bgcolor;

        var title_height = LiteGraph.NODE_TITLE_HEIGHT;
        var low_quality = this.ds.scale < 0.5;

        //render node area depending on shape
        var shape =
            node._shape || node.constructor.shape || LiteGraph.ROUND_SHAPE;

        var title_mode = node.constructor.title_mode;

        var render_title = true;
        if (title_mode == LiteGraph.TRANSPARENT_TITLE || title_mode == LiteGraph.NO_TITLE) {
            render_title = false;
        } else if (title_mode == LiteGraph.AUTOHIDE_TITLE && mouse_over) {
            render_title = true;
        }

        var area = tmp_area;
        area[0] = 0; //x
        area[1] = render_title ? -title_height : 0; //y
        area[2] = size[0] + 1; //w
        area[3] = render_title ? size[1] + title_height : size[1]; //h

        var old_alpha = ctx.globalAlpha;

        //full node shape
        //if(node.flags.collapsed)
        {
            ctx.beginPath();
            if (shape == LiteGraph.BOX_SHAPE || low_quality) {
                ctx.fillRect(area[0], area[1], area[2], area[3]);
            } else if (
                shape == LiteGraph.ROUND_SHAPE ||
                shape == LiteGraph.CARD_SHAPE
            ) {
                ctx.roundRect(
                    area[0],
                    area[1],
                    area[2],
                    area[3],
                    shape == LiteGraph.CARD_SHAPE ? [this.round_radius,this.round_radius,0,0] : [this.round_radius] 
                );
            } else if (shape == LiteGraph.CIRCLE_SHAPE) {
                ctx.arc(
                    size[0] * 0.5,
                    size[1] * 0.5,
                    size[0] * 0.5,
                    0,
                    Math.PI * 2
                );
            }
            ctx.fill();
            if (LiteGraph.NODE_BORDER_COLOR && !low_quality) { /* PATRON: 1px node border matching the panels */
                ctx.shadowColor = "transparent";
                ctx.strokeStyle = LiteGraph.NODE_BORDER_COLOR;
                ctx.lineWidth = 1;
                ctx.stroke();
            }

			//separator
			if(!node.flags.collapsed && render_title)
			{
				ctx.shadowColor = "transparent";
				ctx.fillStyle = "rgba(0,0,0,0.2)";
				ctx.fillRect(0, -0.5, area[2], 0.5); /* PATRON: thinner title/body separator (0.5px) */
			}
        }
        ctx.shadowColor = "transparent";

        if (node.onDrawBackground) {
            node.onDrawBackground(ctx, this, this.canvas, this.graph_mouse );
        }

        //title bg (remember, it is rendered ABOVE the node)
        if (render_title || title_mode == LiteGraph.TRANSPARENT_TITLE) {
            //title bar
            if (node.onDrawTitleBar) {
                node.onDrawTitleBar( ctx, title_height, size, this.ds.scale, fgcolor );
            } else if (
                title_mode != LiteGraph.TRANSPARENT_TITLE &&
                (node.constructor.title_color || this.render_title_colored)
            ) {
                var title_color = node.constructor.title_color || fgcolor;

                if (node.flags.collapsed) {
                    ctx.shadowColor = LiteGraph.DEFAULT_SHADOW_COLOR;
                }

                //* gradient test
                if (this.use_gradients) {
                    var grad = LGraphCanvas.gradients[title_color];
                    if (!grad) {
                        grad = LGraphCanvas.gradients[ title_color ] = ctx.createLinearGradient(0, 0, 400, 0);
                        grad.addColorStop(0, title_color); // TODO refactor: validate color !! prevent DOMException
                        grad.addColorStop(1, "#000");
                    }
                    ctx.fillStyle = grad;
                } else {
                    ctx.fillStyle = title_color;
                }

                //ctx.globalAlpha = 0.5 * old_alpha;
                ctx.beginPath();
                if (shape == LiteGraph.BOX_SHAPE || low_quality) {
                    ctx.rect(0, -title_height, size[0] + 1, title_height);
                } else if (  shape == LiteGraph.ROUND_SHAPE || shape == LiteGraph.CARD_SHAPE ) {
                    ctx.roundRect(
                        0,
                        -title_height,
                        size[0] + 1,
                        title_height,
                        node.flags.collapsed ? [this.round_radius] : [this.round_radius,this.round_radius,0,0]
                    );
                }
                ctx.fill();
                ctx.shadowColor = "transparent";
            }

            var colState = false;
            if (LiteGraph.node_box_coloured_by_mode){
                if(LiteGraph.NODE_MODES_COLORS[node.mode]){
                    colState = LiteGraph.NODE_MODES_COLORS[node.mode];
                }
            }
            if (LiteGraph.node_box_coloured_when_on){
                colState = node.action_triggered ? "#FFF" : (node.execute_triggered ? "#AAA" : colState);
            }
            
            //title box
            var box_size = 10;
            if (node.onDrawTitleBox) {
                node.onDrawTitleBox(ctx, title_height, size, this.ds.scale);
            } else if (
                shape == LiteGraph.ROUND_SHAPE ||
                shape == LiteGraph.CIRCLE_SHAPE ||
                shape == LiteGraph.CARD_SHAPE
            ) {
                if (low_quality) {
                    ctx.fillStyle = "black";
                    ctx.beginPath();
                    ctx.arc(
                        title_height * 0.5,
                        title_height * -0.5,
                        box_size * 0.5 + 1,
                        0,
                        Math.PI * 2
                    );
                    ctx.fill();
                }
                
                ctx.fillStyle = node.boxcolor || colState || LiteGraph.NODE_DEFAULT_BOXCOLOR;
				if(low_quality)
					ctx.fillRect( title_height * 0.5 - box_size *0.5, title_height * -0.5 - box_size *0.5, box_size , box_size  );
				else
				{
					ctx.beginPath();
					ctx.arc(
						title_height * 0.5,
						title_height * -0.5,
						box_size * 0.5,
						0,
						Math.PI * 2
					);
					ctx.fill();
				}
            } else {
                if (low_quality) {
                    ctx.fillStyle = "black";
                    ctx.fillRect(
                        (title_height - box_size) * 0.5 - 1,
                        (title_height + box_size) * -0.5 - 1,
                        box_size + 2,
                        box_size + 2
                    );
                }
                ctx.fillStyle = node.boxcolor || colState || LiteGraph.NODE_DEFAULT_BOXCOLOR;
                ctx.fillRect(
                    (title_height - box_size) * 0.5,
                    (title_height + box_size) * -0.5,
                    box_size,
                    box_size
                );
            }
            ctx.globalAlpha = old_alpha;

            //title text
            if (node.onDrawTitleText) {
                node.onDrawTitleText(
                    ctx,
                    title_height,
                    size,
                    this.ds.scale,
                    this.title_text_font,
                    selected
                );
            }
            if (!low_quality) {
                ctx.font = this.title_text_font;
                var title = String(node.getTitle());
                if (title) {
                    if (selected) {
                        ctx.fillStyle = LiteGraph.NODE_SELECTED_TITLE_COLOR;
                    } else {
                        ctx.fillStyle =
                            node.constructor.title_text_color ||
                            this.node_title_color;
                    }
                    if (node.flags.collapsed) {
                        ctx.textAlign = "left";
                        var measure = ctx.measureText(title);
                        ctx.fillText(
                            title.substr(0,20), //avoid urls too long
                            title_height,// + measure.width * 0.5,
                            LiteGraph.NODE_TITLE_TEXT_Y - title_height
                        );
                        ctx.textAlign = "left";
                    } else {
                        ctx.textAlign = "left";
                        ctx.fillText(
                            title,
                            title_height,
                            LiteGraph.NODE_TITLE_TEXT_Y - title_height
                        );
                    }
                }
            }

			//subgraph box
			if (!node.flags.collapsed && node.subgraph && !node.skip_subgraph_button) {
				var w = LiteGraph.NODE_TITLE_HEIGHT;
				var x = node.size[0] - w;
				var over = LiteGraph.isInsideRectangle( this.graph_mouse[0] - node.pos[0], this.graph_mouse[1] - node.pos[1], x+2, -w+2, w-4, w-4 );
				ctx.fillStyle = over ? "#888" : "#555";
				if( shape == LiteGraph.BOX_SHAPE || low_quality)
					ctx.fillRect(x+2, -w+2, w-4, w-4);
				else
				{
					ctx.beginPath();
					ctx.roundRect(x+2, -w+2, w-4, w-4,[4]);
					ctx.fill();
				}
				ctx.fillStyle = "#333";
				ctx.beginPath();
				ctx.moveTo(x + w * 0.2, -w * 0.6);
				ctx.lineTo(x + w * 0.8, -w * 0.6);
				ctx.lineTo(x + w * 0.5, -w * 0.3);
				ctx.fill();
			}

			//custom title render
            if (node.onDrawTitle) {
                node.onDrawTitle(ctx);
            }
        }

        //render selection marker
        if (selected) {
            if (node.onBounding) {
                node.onBounding(area);
            }

            if (title_mode == LiteGraph.TRANSPARENT_TITLE) {
                area[1] -= title_height;
                area[3] += title_height;
            }
            ctx.lineWidth = 2;       /* PATRON: selection border (was 1) */
            ctx.globalAlpha = 1;     /* PATRON: solid selection border (was 0.8) */
            ctx.beginPath();
            if (shape == LiteGraph.BOX_SHAPE) {
                ctx.rect(
                    area[0],
                    area[1],
                    area[2],
                    area[3]
                );
            } else if (
                shape == LiteGraph.ROUND_SHAPE ||
                (shape == LiteGraph.CARD_SHAPE && node.flags.collapsed)
            ) {
                ctx.roundRect(
                    area[0],
                    area[1],
                    area[2],
                    area[3],
                    [this.round_radius]
                );
            } else if (shape == LiteGraph.CARD_SHAPE) {
                ctx.roundRect(
                    area[0],
                    area[1],
                    area[2],
                    area[3],
                    [this.round_radius,2,this.round_radius,2]
                );
            } else if (shape == LiteGraph.CIRCLE_SHAPE) {
                ctx.arc(
                    size[0] * 0.5,
                    size[1] * 0.5,
                    size[0] * 0.5 + 6,
                    0,
                    Math.PI * 2
                );
            }
            ctx.strokeStyle = LiteGraph.NODE_BOX_OUTLINE_COLOR;
            ctx.stroke();
            ctx.strokeStyle = fgcolor;
            ctx.globalAlpha = 1;
        }
        
        // these counter helps in conditioning drawing based on if the node has been executed or an action occurred
        if (node.execute_triggered>0) node.execute_triggered--;
        if (node.action_triggered>0) node.action_triggered--;
    };

  // ---- LGraphCanvas.prototype.renderLink ----
  LGraphCanvas.prototype.renderLink = function(
        ctx,
        a,
        b,
        link,
        skip_border,
        flow,
        color,
        start_dir,
        end_dir,
        num_sublines
    ) {
        if (link) {
            this.visible_links.push(link);
        }

        //choose color
        if (!color && link) {
            color = link.color || LGraphCanvas.link_type_colors[link.type];
        }
        if (!color) {
            color = this.default_link_color;
        }
        if (link != null && this.highlighted_links[link.id]) {
            color = LiteGraph.LINK_HIGHLIGHT_COLOR || "#FFF"; // PATRON: themeable (default = original #FFF)
        }

        start_dir = start_dir || LiteGraph.RIGHT;
        end_dir = end_dir || LiteGraph.LEFT;

        var dist = LiteGraph.distance(a, b);

        if (this.render_connections_border && this.ds.scale > 0.6) {
            ctx.lineWidth = this.connections_width + 4;
        }
        ctx.lineJoin = "round";
        num_sublines = num_sublines || 1;
        if (num_sublines > 1) {
            ctx.lineWidth = 0.5;
        }

        //begin line shape
        ctx.beginPath();
        for (var i = 0; i < num_sublines; i += 1) {
            var offsety = (i - (num_sublines - 1) * 0.5) * 5;

            if (this.links_render_mode == LiteGraph.SPLINE_LINK) {
                ctx.moveTo(a[0], a[1] + offsety);
                var start_offset_x = 0;
                var start_offset_y = 0;
                var end_offset_x = 0;
                var end_offset_y = 0;
                switch (start_dir) {
                    case LiteGraph.LEFT:
                        start_offset_x = dist * -0.25;
                        break;
                    case LiteGraph.RIGHT:
                        start_offset_x = dist * 0.25;
                        break;
                    case LiteGraph.UP:
                        start_offset_y = dist * -0.25;
                        break;
                    case LiteGraph.DOWN:
                        start_offset_y = dist * 0.25;
                        break;
                }
                switch (end_dir) {
                    case LiteGraph.LEFT:
                        end_offset_x = dist * -0.25;
                        break;
                    case LiteGraph.RIGHT:
                        end_offset_x = dist * 0.25;
                        break;
                    case LiteGraph.UP:
                        end_offset_y = dist * -0.25;
                        break;
                    case LiteGraph.DOWN:
                        end_offset_y = dist * 0.25;
                        break;
                }
                ctx.bezierCurveTo(
                    a[0] + start_offset_x,
                    a[1] + start_offset_y + offsety,
                    b[0] + end_offset_x,
                    b[1] + end_offset_y + offsety,
                    b[0],
                    b[1] + offsety
                );
            } else if (this.links_render_mode == LiteGraph.LINEAR_LINK) {
                ctx.moveTo(a[0], a[1] + offsety);
                var start_offset_x = 0;
                var start_offset_y = 0;
                var end_offset_x = 0;
                var end_offset_y = 0;
                switch (start_dir) {
                    case LiteGraph.LEFT:
                        start_offset_x = -1;
                        break;
                    case LiteGraph.RIGHT:
                        start_offset_x = 1;
                        break;
                    case LiteGraph.UP:
                        start_offset_y = -1;
                        break;
                    case LiteGraph.DOWN:
                        start_offset_y = 1;
                        break;
                }
                switch (end_dir) {
                    case LiteGraph.LEFT:
                        end_offset_x = -1;
                        break;
                    case LiteGraph.RIGHT:
                        end_offset_x = 1;
                        break;
                    case LiteGraph.UP:
                        end_offset_y = -1;
                        break;
                    case LiteGraph.DOWN:
                        end_offset_y = 1;
                        break;
                }
                var l = 15;
                ctx.lineTo(
                    a[0] + start_offset_x * l,
                    a[1] + start_offset_y * l + offsety
                );
                ctx.lineTo(
                    b[0] + end_offset_x * l,
                    b[1] + end_offset_y * l + offsety
                );
                ctx.lineTo(b[0], b[1] + offsety);
            } else if (this.links_render_mode == LiteGraph.STRAIGHT_LINK) {
                ctx.moveTo(a[0], a[1]);
                var start_x = a[0];
                var start_y = a[1];
                var end_x = b[0];
                var end_y = b[1];
                if (start_dir == LiteGraph.RIGHT) {
                    start_x += 10;
                } else {
                    start_y += 10;
                }
                if (end_dir == LiteGraph.LEFT) {
                    end_x -= 10;
                } else {
                    end_y -= 10;
                }
                ctx.lineTo(start_x, start_y);
                ctx.lineTo((start_x + end_x) * 0.5, start_y);
                ctx.lineTo((start_x + end_x) * 0.5, end_y);
                ctx.lineTo(end_x, end_y);
                ctx.lineTo(b[0], b[1]);
            } else {
                return;
            } //unknown
        }

        //rendering the outline of the connection can be a little bit slow
        if (
            this.render_connections_border &&
            this.ds.scale > 0.6 &&
            !skip_border
        ) {
            ctx.strokeStyle = "rgba(0,0,0,0.5)";
            ctx.stroke();
        }

        ctx.lineWidth = this.connections_width;
        ctx.fillStyle = ctx.strokeStyle = color;
        ctx.stroke();
        //end line shape

        var pos = this.computeConnectionPoint(a, b, 0.5, start_dir, end_dir);
        if (link && link._pos) {
            link._pos[0] = pos[0];
            link._pos[1] = pos[1];
        }

        //render arrow in the middle
        if (
            this.ds.scale >= 0.6 &&
            this.highquality_render &&
            end_dir != LiteGraph.CENTER
        ) {
            //render arrow
            if (this.render_connection_arrows) {
                //compute two points in the connection
                var posA = this.computeConnectionPoint(
                    a,
                    b,
                    0.25,
                    start_dir,
                    end_dir
                );
                var posB = this.computeConnectionPoint(
                    a,
                    b,
                    0.26,
                    start_dir,
                    end_dir
                );
                var posC = this.computeConnectionPoint(
                    a,
                    b,
                    0.75,
                    start_dir,
                    end_dir
                );
                var posD = this.computeConnectionPoint(
                    a,
                    b,
                    0.76,
                    start_dir,
                    end_dir
                );

                //compute the angle between them so the arrow points in the right direction
                var angleA = 0;
                var angleB = 0;
                if (this.render_curved_connections) {
                    angleA = -Math.atan2(posB[0] - posA[0], posB[1] - posA[1]);
                    angleB = -Math.atan2(posD[0] - posC[0], posD[1] - posC[1]);
                } else {
                    angleB = angleA = b[1] > a[1] ? 0 : Math.PI;
                }

                //render arrow
                ctx.save();
                ctx.translate(posA[0], posA[1]);
                ctx.rotate(angleA);
                ctx.beginPath();
                ctx.moveTo(-5, -3);
                ctx.lineTo(0, +7);
                ctx.lineTo(+5, -3);
                ctx.fill();
                ctx.restore();
                ctx.save();
                ctx.translate(posC[0], posC[1]);
                ctx.rotate(angleB);
                ctx.beginPath();
                ctx.moveTo(-5, -3);
                ctx.lineTo(0, +7);
                ctx.lineTo(+5, -3);
                ctx.fill();
                ctx.restore();
            }

            //circle
            ctx.beginPath();
            ctx.arc(pos[0], pos[1], 5, 0, Math.PI * 2);
            ctx.fill();
        }

        //render flowing points
        if (flow) {
            ctx.fillStyle = color;
            for (var i = 0; i < 5; ++i) {
                var f = (LiteGraph.getTime() * 0.001 + i * 0.2) % 1;
                var pos = this.computeConnectionPoint(
                    a,
                    b,
                    f,
                    start_dir,
                    end_dir
                );
                ctx.beginPath();
                ctx.arc(pos[0], pos[1], 5, 0, 2 * Math.PI);
                ctx.fill();
            }
        }
    };

  // ---- LGraphCanvas.prototype.processNodeDblClicked ----
  // PATRON: double-clicking a node opens ITS OWN panel. Upstream calls showShowNodePanel()
  // (the black inline title-editor box) + onNodeDblClicked; we replace it entirely so there is
  // no title-edit box — just the block's panel. Uses litegraph's own node-dblclick detection
  // (processMouseDown), so it's reliable and not a coordinate hit-test.
  LGraphCanvas.prototype.processNodeDblClicked = function (n) {
    if (global.PatronProps && global.PatronProps.openBlock) global.PatronProps.openBlock(n);
    this.setDirty(true);
  };

  // ---- LGraphCanvas.prototype.processContextMenu ----
  LGraphCanvas.prototype.processContextMenu = function(node, event) {
        var that = this;
        var canvas = LGraphCanvas.active_canvas;
        var ref_window = canvas.getCanvasWindow();

        var menu_info = null;
        var options = {
            event: event,
            callback: inner_option_clicked,
            extra: node
        };

		if(node)
			options.title = node.getTitle ? node.getTitle() : (node.title || node.type); /* PATRON: friendly title, not the internal type path */

        //check if mouse is in input
        var slot = null;
        if (node) {
            slot = node.getSlotInPosition(event.canvasX, event.canvasY);
            LGraphCanvas.active_node = node;
        }
        // PATRON: no default node context menu (the litegraph junk menu in the middle of a
        // block). Right-clicking a node body does nothing; slot + canvas menus still work.
        if (node && !slot) return;

        if (slot) {
            //on slot
            menu_info = [];
            if (node.getSlotMenuOptions) {
                menu_info = node.getSlotMenuOptions(slot);
            } else {
                if (
                    slot &&
                    slot.output &&
                    slot.output.links &&
                    slot.output.links.length
                ) {
                    menu_info.push({ content: "Disconnect Links", slot: slot });
                }
                var _slot = slot.input || slot.output;
                if (_slot.removable){
                	menu_info.push(
	                    _slot.locked
	                        ? "Cannot remove"
	                        : { content: "Remove Slot", slot: slot }
	                );
            	}
                if (!_slot.nameLocked){
	                menu_info.push({ content: "Rename Slot", slot: slot });
                }
    
            }
            options.title =
                (slot.input ? slot.input.type : slot.output.type) || "*";
            if (slot.input && slot.input.type == LiteGraph.ACTION) {
                options.title = "Action";
            }
            if (slot.output && slot.output.type == LiteGraph.EVENT) {
                options.title = "Event";
            }
        } else {
            if (node) {
                //on node
                menu_info = this.getNodeMenuOptions(node);
            } else {
                menu_info = this.getCanvasMenuOptions();
                var group = this.graph.getGroupOnPos(
                    event.canvasX,
                    event.canvasY
                );
                if (group) {
                    //on group
                    menu_info.push(null, {
                        content: "Edit Group",
                        has_submenu: true,
                        submenu: {
                            title: "Group",
                            extra: group,
                            options: this.getGroupMenuOptions(group)
                        }
                    });
                }
            }
        }

        //show menu
        if (!menu_info) {
            return;
        }

        var menu = new LiteGraph.ContextMenu(menu_info, options, ref_window);

        function inner_option_clicked(v, options, e) {
            if (!v) {
                return;
            }

            if (v.content == "Remove Slot") {
                var info = v.slot;
                node.graph.beforeChange();
                if (info.input) {
                    node.removeInput(info.slot);
                } else if (info.output) {
                    node.removeOutput(info.slot);
                }
                node.graph.afterChange();
                return;
            } else if (v.content == "Disconnect Links") {
                var info = v.slot;
                node.graph.beforeChange();
                if (info.output) {
                    node.disconnectOutput(info.slot);
                } else if (info.input) {
                    node.disconnectInput(info.slot);
                }
                node.graph.afterChange();
                return;
            } else if (v.content == "Rename Slot") {
                var info = v.slot;
                var slot_info = info.input
                    ? node.getInputInfo(info.slot)
                    : node.getOutputInfo(info.slot);
                var dialog = that.createDialog(
                    "<span class='name'>Name</span><input autofocus type='text'/><button>OK</button>",
                    options
                );
                var input = dialog.querySelector("input");
                if (input && slot_info) {
                    input.value = slot_info.label || "";
                }
                var inner = function(){
                	node.graph.beforeChange();
                    if (input.value) {
                        if (slot_info) {
                            slot_info.label = input.value;
                        }
                        that.setDirty(true);
                    }
                    dialog.close();
                    node.graph.afterChange();
                }
                dialog.querySelector("button").addEventListener("click", inner);
                input.addEventListener("keydown", function(e) {
                    dialog.is_modified = true;
                    if (e.keyCode == 27) {
                        //ESC
                        dialog.close();
                    } else if (e.keyCode == 13) {
                        inner(); // save
                    } else if (e.keyCode != 13 && e.target.localName != "textarea") {
                        return;
                    }
                    e.preventDefault();
                    e.stopPropagation();
                });
                input.focus();
            }

            //if(v.callback)
            //	return v.callback.call(that, node, options, e, menu, that, event );
        }
    };

  // ==========================================================================
  // PATRON: many-to-many connections (input FAN-IN).
  //
  // Upstream litegraph already lets one OUTPUT feed MANY inputs (output.links is
  // an array). But each INPUT holds ONE link (input.link is a scalar) — dragging
  // a 2nd wire onto an input disconnects the 1st. Patron needs the mirror image:
  // MANY outputs -> ONE input (fan-in), to match the runtime's per-message fan-in.
  //
  // We add input.links[] (symmetric to output.links[]) and override the handful of
  // methods that assumed one-link-per-input:
  //   connect          - wrap upstream: hide the scalar so it won't disconnect the
  //                      existing wire, then append the new link to input.links[]
  //   disconnectInput  - remove a SPECIFIC link (or all) from input.links[]
  //   removeLink       - pass the specific link id through (was: by slot => nuked all)
  //   drawConnections  - wrap upstream, then render the EXTRA fan-in links it skipped
  //   configure        - rebuild input.links[] from graph.links after a load
  //
  // input.link (scalar) is kept = the LAST link so all the vanilla readers that
  // still use it (getInputData, slot pickup on drag, link highlighting) keep working.
  // Every fan-in link lives in graph.links, so LGraph.serialize already persists them
  // on Save; we only need to rebuild the per-input arrays on load. A slot can opt OUT
  // of fan-in with input.multi === false (falls back to vanilla single-link behavior).
  // ==========================================================================
  var LGraph = global.LGraph;
  if (LGraph && LGraphNode && LGraphCanvas) {
    var _tmpOut = new Float32Array(2);
    var _tmpIn = new Float32Array(2);

    function inputIsMulti(input) { return !!input && input.multi !== false; }

    // ---- LGraphNode.prototype.connect (wrap) ----
    var _origConnect = LGraphNode.prototype.connect;
    LGraphNode.prototype.connect = function (slot, target_node, target_slot) {
      // Resolve just enough to find the target INPUT (upstream re-resolves everything).
      var t_node = target_node;
      if (t_node && t_node.constructor === Number) {
        t_node = this.graph ? this.graph.getNodeById(t_node) : null;
      }
      var t_slot = target_slot == null ? 0 : target_slot;
      var input = null;
      if (t_node && t_node.inputs) {
        if (t_slot != null && t_slot.constructor === String) {
          var idx = t_node.findInputSlot(t_slot);
          if (idx !== -1) { input = t_node.inputs[idx]; }
        } else if (typeof t_slot === "number") {
          input = t_node.inputs[t_slot];
        }
      }
      var multi = inputIsMulti(input);

      // Dedupe: skip if this exact origin-slot -> target-slot edge already exists.
      if (multi && this.graph && input.links && input.links.length) {
        var oslot = (typeof slot === "number") ? slot : this.findOutputSlot(slot);
        for (var e = 0; e < input.links.length; e++) {
          var l = this.graph.links[input.links[e]];
          if (l && l.origin_id === this.id && l.origin_slot === oslot) { return l; }
        }
      }

      // Hide the existing scalar so upstream connect() won't disconnect the old wire.
      var savedScalar = null, hid = false;
      if (multi && input && input.link != null) { savedScalar = input.link; input.link = null; hid = true; }

      var link_info = _origConnect.call(this, slot, target_node, target_slot);

      if (multi && input) {
        if (link_info) {
          if (input.links == null) { input.links = []; }
          if (input.links.indexOf(link_info.id) === -1) { input.links.push(link_info.id); }
          // upstream already set input.link = link_info.id (scalar = last)
        } else if (hid) {
          input.link = savedScalar; // connection was rejected — restore what we hid
        }
      }
      return link_info;
    };

    // Remove a single input link everywhere (graph pool, origin output.links, arrays)
    // and fire the same callbacks upstream disconnectInput does — for ONE link.
    function removeOneInputLink(node, slot, link_id) {
      var input = node.inputs[slot];
      var graph = node.graph;
      if (!input || !graph || link_id == null) { return false; }
      var link_info = graph.links[link_id];
      if (link_info) {
        var origin = graph.getNodeById(link_info.origin_id);
        if (origin) {
          var output = origin.outputs[link_info.origin_slot];
          if (output && output.links && output.links.length) {
            var oi = output.links.indexOf(link_id);
            if (oi !== -1) { output.links.splice(oi, 1); }
          }
          if (origin.onConnectionsChange) {
            origin.onConnectionsChange(LiteGraph.OUTPUT, link_info.origin_slot, false, link_info, output);
          }
          if (graph.onNodeConnectionChange) {
            graph.onNodeConnectionChange(LiteGraph.OUTPUT, origin, link_info.origin_slot);
          }
        }
        delete graph.links[link_id];
        graph._version++;
      }
      if (input.links && input.links.length) {
        var j = input.links.indexOf(link_id);
        if (j !== -1) { input.links.splice(j, 1); }
      }
      if (input.link === link_id) {
        input.link = (input.links && input.links.length) ? input.links[input.links.length - 1] : null;
      }
      if (node.onConnectionsChange) { node.onConnectionsChange(LiteGraph.INPUT, slot, false, link_info, input); }
      if (graph.onNodeConnectionChange) { graph.onNodeConnectionChange(LiteGraph.INPUT, node, slot); }
      return true;
    }

    // ---- LGraphNode.prototype.disconnectInput (override) ----
    // disconnectInput(slot)          -> remove ALL links on that input (node delete, clear)
    // disconnectInput(slot, link_id) -> remove only that one link (fan-in edge delete)
    LGraphNode.prototype.disconnectInput = function (slot, target) {
      if (slot.constructor === String) {
        slot = this.findInputSlot(slot);
        if (slot === -1) { if (LiteGraph.debug) { console.log("Connect: Error, no slot of name " + slot); } return false; }
      } else if (!this.inputs || slot >= this.inputs.length) {
        if (LiteGraph.debug) { console.log("Connect: Error, slot number not found"); }
        return false;
      }
      var input = this.inputs[slot];
      if (!input) { return false; }

      var ids;
      if (typeof target === "number") { ids = [target]; }
      else if (input.links && input.links.length) { ids = input.links.slice(); }
      else if (input.link != null) { ids = [input.link]; }
      else { this.setDirtyCanvas(false, true); return false; }

      for (var i = 0; i < ids.length; i++) { removeOneInputLink(this, slot, ids[i]); }
      this.setDirtyCanvas(false, true);
      if (this.graph) { this.graph.connectionChange(this); }
      return true;
    };

    // ---- LGraph.prototype.removeLink (override) ----
    // Target the SPECIFIC link so deleting one fan-in edge keeps the siblings.
    LGraph.prototype.removeLink = function (link_id) {
      var link = this.links[link_id];
      if (!link) { return; }
      var node = this.getNodeById(link.target_id);
      if (node) { node.disconnectInput(link.target_slot, link_id); }
    };

    // ---- LGraphCanvas.prototype.drawConnections (wrap + post-pass) ----
    // Upstream draws ONE link per input (input.link). We let it run, then draw every
    // ADDITIONAL fan-in link it skipped. (Upstream's own body uses IIFE-local temp
    // vectors we can't reach, so we render the extras with our own — full faithfulness
    // for the primary link, plain curves for the rest via the same renderLink().)
    var _origDrawConnections = LGraphCanvas.prototype.drawConnections;
    LGraphCanvas.prototype.drawConnections = function (ctx) {
      _origDrawConnections.call(this, ctx);
      var graph = this.graph;
      if (!graph || !graph._nodes) { return; }
      ctx.lineWidth = this.connections_width;
      ctx.fillStyle = "#AAA";
      ctx.strokeStyle = "#AAA";
      ctx.globalAlpha = this.editor_alpha;
      var nodes = graph._nodes;
      for (var n = 0; n < nodes.length; n++) {
        var node = nodes[n];
        if (!node.inputs) { continue; }
        for (var i = 0; i < node.inputs.length; i++) {
          var input = node.inputs[i];
          if (!input || !input.links || input.links.length < 2) { continue; }
          var end_pos = node.getConnectionPos(true, i, _tmpIn);
          var end_dir = input.dir || (node.horizontal ? LiteGraph.UP : LiteGraph.LEFT);
          for (var k = 0; k < input.links.length; k++) {
            var link_id = input.links[k];
            if (link_id === input.link) { continue; } // primary already drawn upstream
            var link = graph.links[link_id];
            if (!link) { continue; }
            var start_node = graph.getNodeById(link.origin_id);
            if (!start_node) { continue; }
            var out_slot = start_node.outputs && start_node.outputs[link.origin_slot];
            var start_pos = start_node.getConnectionPos(false, link.origin_slot, _tmpOut);
            var start_dir = (out_slot && out_slot.dir) || (start_node.horizontal ? LiteGraph.DOWN : LiteGraph.RIGHT);
            this.renderLink(ctx, start_pos, end_pos, link, false, 0, null, start_dir, end_dir);
          }
        }
      }
      ctx.globalAlpha = 1;
    };

    // Rebuild input.links[] from the authoritative link pool (graph.links) after a load;
    // upstream configure only restores the scalar input.link.
    function rebuildMultiInputs(graph) {
      if (!graph || !graph._nodes) { return; }
      for (var n = 0; n < graph._nodes.length; n++) {
        var inputs = graph._nodes[n].inputs;
        if (!inputs) { continue; }
        for (var i = 0; i < inputs.length; i++) { if (inputIsMulti(inputs[i])) { inputs[i].links = []; } }
      }
      var ids = Object.keys(graph.links).map(Number).sort(function (a, b) { return a - b; });
      for (var x = 0; x < ids.length; x++) {
        var link = graph.links[ids[x]];
        if (!link) { continue; }
        var tnode = graph.getNodeById(link.target_id);
        if (!tnode || !tnode.inputs) { continue; }
        var input = tnode.inputs[link.target_slot];
        if (!input) { continue; }
        if (inputIsMulti(input)) { if (!input.links) { input.links = []; } input.links.push(link.id); }
        input.link = link.id; // scalar = last
      }
    }

    // ---- LGraph.prototype.configure (wrap) ----
    var _origConfigure = LGraph.prototype.configure;
    LGraph.prototype.configure = function (data, keep_old) {
      var r = _origConfigure.call(this, data, keep_old);
      rebuildMultiInputs(this);
      return r;
    };
  } else {
    console.error("litegraph-patches: many-to-many patch skipped (LGraph/LGraphNode/LGraphCanvas missing)");
  }
})(window);
